services:
  app:
    environment:
      - $
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 3.12-bookworm
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    user: vscode

